version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
       - db_data:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: "my_project_dev"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
  web:
    image: my_project:latest
    ports:
      - "4000:4000"
      - "14000:14000"
      - "24000:24000"
    depends_on:
      - db
    env_file:
      - config/docker.env

volumes:
    db_data:
